import { ArrowUpRight, Check } from "lucide-react";
import { Link } from "wouter";
import { ContactCta, PageShell } from "@/components/SiteShell";
import { SectionIntro } from "@/components/Editorial";
import { founder, processSteps, services, stack } from "@/data/content";

export default function About() {
  return <PageShell><main>
    <section className="page-hero"><div className="container page-hero-grid"><p className="eyebrow">About us / Cullen Consults</p><h1>Small enough to care.<br /><em>Sharp enough to move.</em></h1><p>We are an ecommerce growth agency founded by Benedict Cullen, dedicated to building online stores that not only look elite but also drive high-volume sales and sustainable growth.</p></div></section>
    <section className="section about-intro"><div className="container split-copy"><div className="split-label"><span>01</span><span>Our point of view</span></div><div><h2>Design is the visible part of a much bigger decision.</h2><p>With a strong foundation in ecommerce strategy, digital marketing, and conversion-focused design, our team brings ideas to life through sleek Shopify layouts, high-converting product pages, and seamless user experiences.</p><p>Our goal is to help brands build trust, engage customers, and scale effectively in the digital marketplace — without losing the character that made them worth noticing.</p></div></div></section>
    <section className="section section-paper"><div className="container"><SectionIntro index="02" eyebrow="Capabilities" title="One partner across the growth surface."><p>We bring strategy, design, and marketing into the same room so the work does not lose momentum between disciplines.</p></SectionIntro><div className="about-services">{services.map((service) => <div className="about-service" key={service.number}><span>{service.number}</span><h3>{service.title}</h3><p>{service.summary}</p><ul>{service.bullets.map((bullet) => <li key={bullet}><Check size={14} />{bullet}</li>)}</ul></div>)}</div></div></section>
    <section className="section about-founder"><div className="container about-founder-grid"><div><p className="eyebrow">03 / The person behind the work</p><h2>Meet Benedict<br /><span>Cullen.</span></h2><p>{founder.bio}</p><p className="mb-3">From ecommerce roots to a full-scale growth agency, the path has been shaped by a passion for purposeful, results-driven online experiences — blending strategy, design, and marketing into every Shopify store we build.</p><Link href="/contact" className="text-link">Work with Cullen Consults <ArrowUpRight size={15} /></Link></div><div className="portrait-card"><img src={founder.portrait} alt="Benedict Cullen" loading="lazy" decoding="async" /><div><span>Founder & agency lead</span><strong>Benedict Cullen</strong></div></div></div></section>
    <section className="section stack-section"><div className="container"><SectionIntro index="04" eyebrow="Our tech stack" title="The tools stay quiet. The thinking does the work."><p>Each tool supports a specific part of how we strategize, design, and deliver results.</p></SectionIntro><div className="stack-grid">{stack.map((item, index) => <div className="stack-card" key={item.name}><div className="stack-card-top"><span className="stack-index">0{index + 1}</span><img className={`stack-logo${item.logoWide ? " stack-logo--wide" : ""}`} src={item.logo} alt="" /></div><small>{item.descriptor}</small><h3>{item.name}</h3><p>{item.text}</p></div>)}</div></div></section>
    <section className="section section-dark about-process"><div className="container"><SectionIntro index="05" eyebrow="Design with strategy and creativity" title="A process you can see." dark><p>Our approach combines research, creativity, and execution to analyze business problems, design purposeful solutions, and build digital experiences that connect with an audience.</p></SectionIntro><div className="process-list process-list--dark">{processSteps.map((step) => <div className="process-row" key={step.number}><span className="process-number">{step.number}</span><h3>{step.title}</h3><p>{step.text}</p><ArrowUpRight size={20} /></div>)}</div></div></section>
    <ContactCta eyebrow="06 / Let’s work together" title="Your next best decision could be a conversation." />
  </main></PageShell>;
}
