import { ArrowDown, ArrowUpRight, Check, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { ArticleCard, ProjectCard, SectionIntro, StatsStrip } from "@/components/Editorial";
import { ContactCta, PageShell } from "@/components/SiteShell";
import { articles, currentYearRange, founder, processSteps, projects, services, testimonials } from "@/data/content";

export default function Home() {
  return <PageShell><main>
    <section className="hero"><div className="container hero-grid"><div className="hero-kicker"><span className="hero-orb"><Sparkles size={16} /></span><span>Independent ecommerce growth agency<br />for brands with somewhere to go.</span></div><div className="hero-copy"><p className="eyebrow">Cullen Consults / {currentYearRange()}</p><h1>Make the store<br /><em>earn</em> its attention.</h1><p className="hero-lede">We turn ecommerce ambition into clearer strategy, sharper design, and digital storefronts built to move people from curious to committed.</p><div className="hero-actions"><Link href="/contact" className="button-link button-link--lime">Start a focused conversation <ArrowUpRight size={17} /></Link><Link href="/projects" className="text-link">See selected work <ArrowDown size={15} /></Link></div></div><div className="hero-stamp"><span>CC</span><small>Strategy<br />Design<br />Growth</small></div></div><div className="container hero-bottom"></div></section>
    <section className="section section-paper"><div className="container"><SectionIntro index="01" eyebrow="What we do" title="Growth is a design problem, too."><p>As an ecommerce agency, we create online experiences that blend smart design, marketing, and conversion tactics to help your brand grow and scale with confidence.</p></SectionIntro><div className="service-list">{services.map((service) => <article className="service-row" key={service.number}><div className="service-number">{service.number}</div><div className="service-main"><h3>{service.title}</h3><p>{service.summary}</p></div><ul>{service.bullets.map((bullet) => <li key={bullet}><Check size={14} />{bullet}</li>)}</ul><ArrowUpRight className="service-arrow" size={23} /></article>)}</div></div></section>
    <section className="section founder-section"><div className="container founder-grid"><div className="founder-image-wrap"><img src={founder.portrait} alt="Benedict Cullen portrait" loading="lazy" decoding="async" /><div className="image-note">01 / founder portrait</div></div><div className="founder-copy"><p className="eyebrow">02 / who is Cullen?</p><h2>A founder’s eye.<br /><span>An operator’s focus.</span></h2><p>{founder.bio}</p><p className="founder-detail">Cullen Consults is built for ecommerce brands that want less noise between their ambition and the next sale — combining strategic architecture, high-performing ads, and direct mentorship.</p><a href="https://benedictcullen.vercel.app/" target="_blank" rel="noreferrer" className="text-link">Know more about Benedict <ArrowUpRight size={15} /></a></div></div></section>
    <section className="section projects-section"><div className="container"><SectionIntro index="03" eyebrow="Selected work" title="The work should make the strategy visible."><p>A selection of storefronts, interfaces, and growth systems shaped around the real business problem underneath.</p></SectionIntro><div className="project-grid">{projects.slice(0, 4).map((project, index) => <ProjectCard key={project.slug} project={project} featured={index === 0} />)}</div><div className="section-action"><Link className="button-link" href="/projects">Browse all projects <ArrowUpRight size={17} /></Link></div></div></section>
    <section className="section section-dark proof-section"><div className="container"><SectionIntro index="04" eyebrow="Proof, not noise" title="A clear point of view travels further." dark><p>Trust is built through the details: the way the challenge is framed, the way a system is explained, and the way a customer moves through the work.</p></SectionIntro><StatsStrip /><div className="testimonial-grid">{testimonials.slice(0, 3).map((item) => <figure key={item.name}><blockquote>“{item.quote}”</blockquote><figcaption><strong>{item.name}</strong><span>{item.role}</span></figcaption></figure>)}</div></div></section>
    <section className="section process-section"><div className="container"><SectionIntro index="05" eyebrow="How we work" title="Good work has a rhythm."><p>Research first. Make the important decision visible. Then keep refining until the experience feels inevitable.</p></SectionIntro><div className="process-list">{processSteps.map((step) => <div className="process-row" key={step.number}><span className="process-number">{step.number}</span><h3>{step.title}</h3><p>{step.text}</p><ArrowUpRight size={20} /></div>)}</div></div></section>
    <section className="section journal-section"><div className="container"><SectionIntro index="06" eyebrow="From the journal" title="Ideas for the space between clicks."><p>Notes on design, ecommerce, and building digital experiences that people can actually use.</p></SectionIntro><div className="article-grid">{articles.slice(0, 3).map((article, index) => <ArticleCard key={article.slug} article={article} featured={index === 0} />)}</div><div className="section-action"><Link className="text-link" href="/blogs">Browse the full journal <ArrowUpRight size={15} /></Link></div></div></section>
    <ContactCta />
  </main></PageShell>;
}
